/* Site form data */
export interface Site{
    /* Site general data */
    name : string,
    code : string,
    state: string,
    lga: string,
    street_address: string,
    site_measurement: number,
    site_level: number,
    site_longitude: number,
    site_latitude: number,
    site_comment: string,
    /* Gate */
    gate_description: string,
    gate_size: number,
    gate_thickness: number,
    gate_quantity: number,
    gate_condition: string,
    gate_damage: number,
    gate_cost_of_repair: number,
    /* Fence */
    fence_descriptio: string,
    fence_height: number,
    perimeter: number,
    fence_quantity: number,
    fence_concrete_work: number,
    fence_block_work: number,
    fence_form_work: number,
    fence_reinforcement_work: number,
    fence_rendering: number,
    fence_barb_wire: number,
    fence_condition: string,
    fence_damage: number,
    fence_cost_of_repair: number,
    /* Roads */
    roads_description: string,
    roads_width: number,
    roads_length: number,
    roads_quantity: number,
    roads_surface_dressing: number,
    roads_condition: string,
    roads_damage: number,
    roads_cost_of_repair: number
    /* Paths & pavement */
    paths_description: string,
    paths_width: number,
    paths_length: number,
    paths_quantity: number,
    paths_surface_dressing: number,
    paths_condition: string,
    paths_damage: number,
    paths_cost_of_repair: number,
    /* Driveway */
    driveway_description: string,
    driveway_width: number,
    driveway_length: number,
    driveway_quantity: number,
    driveway_surface_dressing: number,
    driveway_condition: string,
    driveway_damage: number,
    driveway_cost_of_repair: number,
    /* Drainage */
    drainage_description: string,
    drainage_depth: number,
    drainage_length: number,
    drainage_quantity: number,
    drainage_concrete_work: number,
    drainage_block_work, number,
    drainage_form_work: number,
    drainage_reinforcement: number,
    drainage_rendering: number,
    drainage_condition: string,
    drainage_damage: number,
    drainage_cost_of_repair: number,
    /* Electricity */
    electricity_description: string,
    electricity_piping_and_accessories: number,
    electricity_cabling: number,
    electricity_quantity: number,
    electricity_sources: string,
    electricity_condition: string,
    electricity_damage: number,
    electricity_cost_of_repair,
    /* Water */
    water_description: string,
    water_piping_and_accessories: number,
    water_cabling: number,
    water_sources: string,
    water_condition: string,
    water_damage: number,
    water_cost_of_repair,
}